org: system
space: system
space-developer:
  ldap_users: []
  users:
  - admin
  - jpressley
  saml_users: []
  ldap_groups:
  - cf_admin
space-manager:
  ldap_users: []
  users:
  - admin
  - jpressley
  saml_users: []
  ldap_groups:
  - cf_admin
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - cf_users
allow-ssh: true
enable-space-quota: false
enable-security-group: false
enable-unassign-security-group: true
enable-remove-users: false
isolation_segment: ""
named-security-groups: []
paid-service-plans-allowed: false
named_quota: ""
metadata: null
