---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.tanzu-gss-labs.vmware.com/docker-hub-cache/pivotalservices/cf-mgmt
    tag: "1.0.58"
    insecure_registries:
    - harbor.tanzu-gss-labs.vmware.com

inputs:
  - name: config-repo

params:
  SYSTEM_DOMAIN:
  USER_ID:
  PASSWORD:
  CONFIG_DIR:
  CLIENT_SECRET:
  LDAP_USER:
  LDAP_PASSWORD:
  LDAP_SERVER:
  LOG_LEVEL:
  CF_MGMT_COMMAND:
run:
  path: config-repo/ci/tasks/cf-mgmt.sh
