org: system
org-billingmanager:
  ldap_users: []
  users:
  - admin
  - jpressley
  saml_users: []
  ldap_groups:
  - cf_admin
org-manager:
  ldap_users: []
  users:
  - admin
  - jpressley
  saml_users: []
  ldap_groups:
  - cf_admin
org-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - cf_users
private-domains:
- run-13.slot-59.pez.vmware.com
enable-remove-private-domains: false
shared-private-domains: []
enable-remove-shared-private-domains: false
enable-org-quota: false
paid-service-plans-allowed: false
enable-remove-users: false
default_isolation_segment: ""
named_quota: runaway
metadata: null
