enabled: true
#ldapHost: ldap.slot-59.pez.vmware.com
ldapPort: 636
use_tls: true
#bindDN: cn=bind,ou=Users,dc=tanzu,dc=vmware,dc=com
userSearchBase: ou=Users,dc=tanzu,dc=vmware,dc=com
userNameAttribute: uid
userMailAttribute: uid
userObjectClass: inetOrgPerson
groupSearchBase: ou=Groups,dc=tanzu,dc=vmware,dc=com
groupAttribute: memberUid
groupObjectClass: posixGroup
origin: ldap
insecure_skip_verify: false
ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIGLjCCBBagAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgasxCzAJBgNVBAYTAlVT
  MRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxvIEFsdG8xDzANBgNV
  BAoMBlZNd2FyZTEWMBQGA1UECwwNTUFQQlUgU3VwcG9ydDEdMBsGA1UEAwwUU3Vw
  cG9ydCBMYWJzIFJvb3QgQ0ExKzApBgkqhkiG9w0BCQEWHHB2dGwtc3VwcG9ydC1s
  YWJzQHZtd2FyZS5jb20wHhcNMjAwNzIwMDEzOTMyWhcNMzAwNzE4MDEzOTMyWjCB
  nzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExDzANBgNVBAoMBlZN
  d2FyZTEWMBQGA1UECwwNTUFQQlUgU3VwcG9ydDElMCMGA1UEAwwcU3VwcG9ydCBM
  YWJzIEludGVybWVkaWF0ZSBDQTErMCkGCSqGSIb3DQEJARYccHZ0bC1zdXBwb3J0
  LWxhYnNAdm13YXJlLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
  ALiJjK9dhkv2ewRfDsug2qDhtxMoUEOPZeDITUQcuWwUqhHioT4pBEKsvvMamikN
  MRq5E4C0YuVRw6B+GNJ7R2RqaW9lfYasHgTR8K0016AgpZ10I9vI+rwZCPQM3nmi
  rDNDi+P7JMK/+0yy1HTtc5iJ8k3jHqr3MkVMQmb4m/6ogR46cmSjGuUcl7MEFdU/
  ipLCynMS2tADFMuHqjnyBFgIpsh/INBBvjgigJTQem5OWNt2ztiZapiTMPhMY0Dd
  y7UVNWv1lYuddIltLtmeKwU1wIpStLOcGF/DdhFIZ8TSp+7CAFblYlJzT1/iszGY
  69NAF4QAEd5lG+BeAQmZ6Qw0G2YZcCVgiq+3U7HJaMq9E7hNe8/CZDPt67b+9kOZ
  Z4yvykkhYgYQpYzJIksWA8ibihscm7hFRuubqSWDkel2YAR0qdNDfJJqpHIP4+28
  uLUQEs1TiTvdvLEr0i9Ek7B5jY/mpvj89JSk5f6753jsUc5P99jkjfsIROOFY+T1
  HnWmCPBsyDo9nbiCspwer23GlghSUybzvAn5hysTZKIlKYSgJvWlbAaCLOVJv5Sm
  DahQtdlDGNWRp7BFC0XvpZNFTkkRdAQVeVjIZRpcwFbkBh7oealkNG521odnDY8t
  cn2uio/8jptUs7XDQy0D+osE3fJ4WLURUoignO8we8aBAgMBAAGjZjBkMB0GA1Ud
  DgQWBBRjI90rfZRDqgo6O3yVZ8gVosh55jAfBgNVHSMEGDAWgBSracseMmGAc8yg
  wo4jJDOgReTatTASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAN
  BgkqhkiG9w0BAQsFAAOCAgEAAH90kIoUUdLOQQIwQdgb/JQVyzRYAIHOmt4hTaoY
  CjFr50kl9DEeIOJXoDqxbpekO1elaCnTWa5ep+f63e1arSixOQsui3zE/kFn0zfX
  vF4iqz2XI4vDDpRvR1uDQFNAXTUq9OpmHAGiamijnQf+59bZ8Du8W6fOPTxPulYK
  U1E5A+syB4flOTo4xlFDPyYZ1A9/r9p98Tgbl+QMhtUcvqaCJAuTlv29FdlydYuy
  HAKDNS3TKaitPazsJxjpiqlIWywZqAoXvLaCt9e7gWE4PeqH50BRj4gaPMqIpVSg
  Qyy0lMERYeuNl8Y1u4csSQOgZePsEKmsBqB6zW5YEc+6sIp7oS7cU0vnzBzq+cqf
  r+yhNoeU2G1wVAP7iTfOrM/jarYThCK+qungCjtvu+Rpm2ijIazPySeHVwt3UW9B
  57lLoHmZr0iXaCnDj9yR/BEjLwuaCfI1A7RINcRFSP/4Jhrn0BAZemEcck1wmEoT
  zIizXliGpO2XGQO9D+RxFM75X8VE1egqiI6uCLsRuXUbkc6rUadkAL8bQYVHYevQ
  CFy0U9RlAx8cUX/WebttxwzO14HHWL4fGjg3GlSHoK5iGbECLqnkLbD5VsYWCEnj
  cxbBuHZFV8eJpoK9jjoR0+4fBZy2jZPSO7deLnDSJ+0IJj+FDW3aO5g6HiSWfLmM
  bSY=
  -----END CERTIFICATE-----
useIDForSAMLUser: false
minTLSVersion: 1.0
maxTLSVersion: 1.3
