enabled: true
ldapPort: 636
use_tls: true
userSearchBase: ou=users,dc=tanzu,dc=vmware,dc=com
userNameAttribute: uid
userObjectClass: inetOrgPerson
groupSearchBase: ou=groups,dc=tanzu,dc=vmware,dc=com
groupAttribute: memberUid
groupObjectClass: posixGroup
origin: ldap
insecure_skip_verify: true
ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIESTCCAjGgAwIBAgIMYKKzqjSwwd4WwmEOMA0GCSqGSIb3DQEBCwUAMBAxDjAM
  BgNVBAMTBVRhbnp1MB4XDTIxMDUxNzE4MTkyMloXDTIyMDUxNzE4MTkyMlowPTEp
  MCcGA1UEAxMgb3BzbWdyLTEzLnNsb3QtNTkucGV6LnZtd2FyZS5jb20xEDAOBgNV
  BAoTB1Bpdm90YWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCSV+/N
  GCbG6ot7W7JmMgBvmDRxR/vXd32FO8NbPMRkmVsNJ0JlnFZ5lFvz2PBdOFwT3ZKa
  9PC0dFMMmwe0YyUsWfbF7mGsuUI2ehv2IqMSf3/55MXpxc1QmKDJHxId50R+vNw4
  jUj0iIp+qKf2eZnMEXTPdHOlvI4u2aFrQS0E3MgKVW/fq6vxq5xtDzSTA4OtQbsG
  T7zZv8TB+sYfJvB4KiZ2T2UkeRZEeyv5poC43arkLGt7IfoN10b/He4FRtI33Sgh
  oUTYvH5xx3vUXVzSalCxFnhe3nc8r2V9FXhzZq46P5jZtxrX370H/VtHofjo+hAf
  g6hKVtZvxw4zZY5NAgMBAAGjdjB0MAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYI
  KwYBBQUHAwEwDwYDVR0PAQH/BAUDAwegADAdBgNVHQ4EFgQUGqHD0zGJ14yF9kO6
  vhIDT+7OQFgwHwYDVR0jBBgwFoAUg7D/0PqnILMAsC+/YB4ypav5vAwwDQYJKoZI
  hvcNAQELBQADggIBAGXSDUZgufYnc+RRNA3ZLqD45Nyk33S9//Z6ZEcHhlOVrFAC
  xxuyh5wioVNIuUSqaEPfXx8N8FvAo9e/TXY4qsEP+AhkYaeqzCCPgvSl7Cr6/eDi
  vVRy8GJOYqLXyB3IoBTAyxKwTevE6QqGAzxW7Iw3WIlC1SPrwPRDlVpADpZPaCR3
  4z8KNIt88QgEIHFygzc0coXUKD+Z75KLaQM0kF5scj/eovLhWrZjLtyztF0Kj46Q
  pEsk20aRYi2W1SSjRf0oM4RRUsXmoX7MV9Y5m0rt4R4G/8yqlxBSz4Xe3cHyPKnS
  /FHoeOOBCKL21Bxr5H+xcWMBvyrMFFGhAcg0gTW98SaeFAbboR2sK13B1xmjHSpw
  Jnebx4tVA/0ks0qvOSmbXl3Q3vSUhqBb8rLbmVh3QJm9Pvcu65vjlHL70lhKztDY
  X11DbDUbODd/6hB9CHvZQncoWxvMkjp4P+K/vnlvNqXQCp7LyPAK8XnUcY8iZrW1
  fRW5wft3I3oz/imrnDWYo5e8tmdcsSdaJSsBhuwcNNc193+kDmlvHIFxzU336ZAG
  rMAqoLno1UZ9mqky7BqxzLabpLrN4QoBcMArF21CV9PTVlbLegABfGzYMjR3CLI6
  I2XztQUIdSL2RcGoiYO0thkslGOgikE3VKDs9Zg014WN1YD5dgpaSA+gCYln
  -----END CERTIFICATE-----
useIDForSAMLUser: false
minTLSVersion: 1.0
maxTLSVersion: 1.3
