space-developer:
  ldap_users: []
  users:
  - jpressley
  saml_users: []
  ldap_groups:
  - ldap_jpressley
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
