space-developer:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - ldap_admin
space-auditor:
  ldap_users: []
  users:
  - jpressley
  saml_users: []
  ldap_groups:
  - ldap_users
