space-developer:
  ldap_users:
  - jsmith
  - swalls
  users: []
  saml_users: []
  ldap_groups:
  - cf_users
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - cf_admin
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
