org: jsmith
space: dev
space-developer:
  ldap_users:
  - jsmith
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users:
  - jsmith
  users: []
  saml_users: []
  ldap_groups:
  - cf_admin
space-auditor:
  ldap_users:
  - jsmith
  users:
  - jpressley
  saml_users: []
  ldap_groups:
  - cf_users
allow-ssh: true
enable-space-quota: false
enable-security-group: false
enable-unassign-security-group: true
enable-remove-users: false
isolation_segment: "isoseg"
named-security-groups: []
paid-service-plans-allowed: false
named_quota: ""
metadata: null
