org: dev
org-billingmanager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
org-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - ldap_admin
org-auditor:
  ldap_users: []
  users:
  - jpressley
  saml_users: []
  ldap_groups:
  - ldap_admin
  - ldap_users
private-domains: []
enable-remove-private-domains: false
shared-private-domains: []
enable-remove-shared-private-domains: false
enable-org-quota: false
paid-service-plans-allowed: false
enable-remove-users: true
default_isolation_segment: "isoseg"
named_quota: default
metadata: null
