org: jpressley
space: dev
space-developer:
  ldap_users:
  - jsmith
  - swalls
  users:
  - admin
  - jpressley
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users:
  users:
  - admin
  - jpressley
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
allow-ssh: false
enable-space-quota: true
enable-security-group: false
enable-unassign-security-group: true
enable-remove-users: false
isolation_segment: "isoseg"
named-security-groups: []
paid-service-plans-allowed: false
named_quota: ""
metadata: null
