org: swalls
org-billingmanager:
  ldap_users:
  - swalls
  users: []
  saml_users: []
  ldap_groups: []
org-manager:
  ldap_users:
  - swalls
  users: []
  saml_users: []
  ldap_groups:
  - cf_admin
org-auditor:
  ldap_users:
  - swalls
  users:
  - jpressley
  saml_users: []
  ldap_groups:
  - cf_users
private-domains: []
enable-remove-private-domains: false
shared-private-domains: []
enable-remove-shared-private-domains: false
enable-org-quota: false
paid-service-plans-allowed: false
enable-remove-users: false
default_isolation_segment: "isoseg"
named_quota: default
metadata: null
